/* Parser.java */
/* Generated by: ParserGeneratorCC: Do not edit this line. Parser.java */
package parse;

import io.questdb.griffin.model.ExpressionNode;
import io.questdb.std.ObjectPool;
import java.util.ArrayDeque;
import java.util.Deque;

public class Parser implements ParserConstants {
    private ObjectPool<ExpressionNode> sqlNodePool = new ObjectPool<ExpressionNode>(ExpressionNode.FACTORY, 100);
    private final Deque<ExpressionNode> stack = new ArrayDeque<>();
    public ExpressionNode selectNode, fromNode, whereNode;

    public Parser() {
    }

    public void parse(String args) throws Exception {
        stack.clear();
        selectNode = fromNode = whereNode = null;
        ReInit(args);
        SQLStatement();
        stack.clear();
    }

    private void popSelect(String modifier) {
        pop(ExpressionNode.QUERY, "SELECT", 0);
        selectNode = stack.pop();
    }

    private void popFrom() {
        pop(ExpressionNode.QUERY, "FROM", 0);
        fromNode = stack.pop();
    }

    private void popWhere() {
        pop(ExpressionNode.QUERY, "WHERE", 0);
        whereNode = stack.pop();
    }

    private void push(int type, Token token) {
        ExpressionNode newNode = sqlNodePool.next().of(type, token.image, Integer.MIN_VALUE, token.beginColumn);
        stack.push(newNode);
    }

    private void push(int type, CharSequence token, int position) {
        ExpressionNode newNode = sqlNodePool.next().of(type, token, Integer.MIN_VALUE, position);
        stack.push(newNode);
    }

    private void pop(int type, CharSequence token, int position) {
        pop(type, token, position, stack.size());
    }

    private void pop(int type, CharSequence token, int position, int parameters) {
        ExpressionNode newNode = sqlNodePool.next().of(type, token, Integer.MIN_VALUE, position);
        assert stack.size() >= parameters;
        switch(parameters) {
            case 0:
                break;
            case 1:
                newNode.rhs = stack.pop();
                break;
            case 2:
                newNode.rhs = stack.pop();
                newNode.lhs = stack.pop();
                break;
            default:
               for (int i = 0; i < parameters; i++) {
                   newNode.args.add(stack.pop());
               }
               break;
        }
        stack.push(newNode);
    }

    private void replace(int type, CharSequence token, int position, int parameters) {
        ExpressionNode newNode = sqlNodePool.next().of(type, token, Integer.MIN_VALUE, position);
        assert stack.size() >= parameters;
        for(int i = 0; i < parameters; i++) {
            stack.pop();
        }
        stack.push(newNode);
    }

  final public void BindVariable() throws ParseException {
    switch (jj_ntk == -1 ? jj_ntk_f() : jj_ntk) {
    case S_BIND:{
      jj_consume_token(S_BIND);
      break;
      }
    case 66:{
      jj_consume_token(66);
      switch (jj_ntk == -1 ? jj_ntk_f() : jj_ntk) {
      case S_NUMBER:{
        jj_consume_token(S_NUMBER);
        break;
        }
      case S_IDENTIFIER:{
        jj_consume_token(S_IDENTIFIER);
        break;
        }
      default:
        jj_la1[0] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      break;
      }
    default:
      jj_la1[1] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
}

  final public void BasicDataTypeDefinition() throws ParseException {
    switch (jj_ntk == -1 ? jj_ntk_f() : jj_ntk) {
    case K_BOOLEAN:{
      jj_consume_token(K_BOOLEAN);
      break;
      }
    case 67:{
      jj_consume_token(67);
      break;
      }
    case 68:{
      jj_consume_token(68);
      break;
      }
    case K_CHAR:{
      jj_consume_token(K_CHAR);
      break;
      }
    case 69:{
      jj_consume_token(69);
      break;
      }
    case K_FLOAT:{
      jj_consume_token(K_FLOAT);
      break;
      }
    case 70:{
      jj_consume_token(70);
      break;
      }
    case K_STRING:{
      jj_consume_token(K_STRING);
      break;
      }
    case 71:{
      jj_consume_token(71);
      break;
      }
    case K_DATE:{
      jj_consume_token(K_DATE);
      break;
      }
    case 72:{
      jj_consume_token(72);
      break;
      }
    case K_DOUBLE:{
      jj_consume_token(K_DOUBLE);
      break;
      }
    case 73:{
      jj_consume_token(73);
      break;
      }
    case 74:{
      jj_consume_token(74);
      break;
      }
    default:
      jj_la1[2] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
push(ExpressionNode.CONSTANT, token);
}

  final public void SQLStatement() throws ParseException {
    switch (jj_ntk == -1 ? jj_ntk_f() : jj_ntk) {
    case 75:{
      InsertStatement();
      break;
      }
    case K_SELECT:
    case 76:{
      QueryStatement();
      break;
      }
    default:
      jj_la1[3] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
}

  final public void InsertStatement() throws ParseException {
    jj_consume_token(75);
    jj_consume_token(K_INTO);
    TableName();

    if (jj_2_1(2)) {
      jj_consume_token(76);
      TableColumn();
      label_1:
      while (true) {
        switch (jj_ntk == -1 ? jj_ntk_f() : jj_ntk) {
        case 77:{
          break;
          }
        default:
          jj_la1[4] = jj_gen;
          break label_1;
        }
        jj_consume_token(77);
        TableColumn();
      }
      jj_consume_token(78);
    } else {
      ;
    }
    switch (jj_ntk == -1 ? jj_ntk_f() : jj_ntk) {
    case K_VALUES:{
      jj_consume_token(K_VALUES);
      jj_consume_token(76);
      SqlExpressionList();
      jj_consume_token(78);
      break;
      }
    case K_SELECT:
    case 76:{
      SubQuery();
      break;
      }
    default:
      jj_la1[5] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    jj_consume_token(79);
}

  final public void QueryStatement() throws ParseException {
    SelectStatement();
    switch (jj_ntk == -1 ? jj_ntk_f() : jj_ntk) {
    case 79:{
      jj_consume_token(79);
      break;
      }
    case 0:{
      jj_consume_token(0);
      break;
      }
    default:
      jj_la1[6] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
}

  final public void SqlExpression() throws ParseException {
    SqlAndExpression();
    label_2:
    while (true) {
      switch (jj_ntk == -1 ? jj_ntk_f() : jj_ntk) {
      case K_OR:{
        break;
        }
      default:
        jj_la1[7] = jj_gen;
        break label_2;
      }
      jj_consume_token(K_OR);
      SqlAndExpression();
pop(ExpressionNode.FUNCTION, "OR", token.beginColumn, 2);
    }
}

  final public void SqlAndExpression() throws ParseException {
    SqlUnaryLogicalExpression();
    label_3:
    while (true) {
      switch (jj_ntk == -1 ? jj_ntk_f() : jj_ntk) {
      case K_AND:{
        break;
        }
      default:
        jj_la1[8] = jj_gen;
        break label_3;
      }
      jj_consume_token(K_AND);
      SqlUnaryLogicalExpression();
pop(ExpressionNode.FUNCTION, "AND", token.beginColumn, 2);
    }
}

  final public void SqlUnaryLogicalExpression() throws ParseException {boolean inverted = false;
    switch (jj_ntk == -1 ? jj_ntk_f() : jj_ntk) {
    case K_NOT:{
      jj_consume_token(K_NOT);
inverted = true;
      break;
      }
    default:
      jj_la1[9] = jj_gen;
      ;
    }
    SqlRelationalExpression();
if (inverted) {
        pop(ExpressionNode.FUNCTION, "NOT", token.beginColumn, 1);
    }
}

  final public void SqlRelationalExpression() throws ParseException {CharSequence operation;
    SqlSimpleExpression();
    switch (jj_ntk == -1 ? jj_ntk_f() : jj_ntk) {
    case K_BETWEEN:
    case K_IN:
    case K_IS:
    case K_LIKE:
    case K_NOT:
    case 86:
    case 87:
    case 88:
    case 89:
    case 90:{
      switch (jj_ntk == -1 ? jj_ntk_f() : jj_ntk) {
      case 86:
      case 87:
      case 88:
      case 89:
      case 90:{
        Relop();
operation = token.image;
        SqlSimpleExpression();
pop(ExpressionNode.OPERATION, operation, token.beginColumn, 2);
        break;
        }
      default:
        jj_la1[10] = jj_gen;
        if (jj_2_2(2)) {
          SqlInClause();
        } else if (jj_2_3(2)) {
          SqlBetweenClause();
        } else if (jj_2_4(2)) {
          SqlLikeClause();
        } else {
          switch (jj_ntk == -1 ? jj_ntk_f() : jj_ntk) {
          case K_IS:{
            IsNullClause();
            break;
            }
          default:
            jj_la1[11] = jj_gen;
            jj_consume_token(-1);
            throw new ParseException();
          }
        }
      }
      break;
      }
    default:
      jj_la1[12] = jj_gen;
      ;
    }
}

  final public void SqlExpressionList() throws ParseException {
    SqlExpression();
    label_4:
    while (true) {
      switch (jj_ntk == -1 ? jj_ntk_f() : jj_ntk) {
      case 77:{
        break;
        }
      default:
        jj_la1[13] = jj_gen;
        break label_4;
      }
      jj_consume_token(77);
      SqlExpression();
    }
}

  final public void SqlInClause() throws ParseException {
    switch (jj_ntk == -1 ? jj_ntk_f() : jj_ntk) {
    case K_NOT:{
      jj_consume_token(K_NOT);
      break;
      }
    default:
      jj_la1[14] = jj_gen;
      ;
    }
    jj_consume_token(K_IN);
    jj_consume_token(76);
    SqlExpressionList();
    jj_consume_token(78);
}

  final public void SqlBetweenClause() throws ParseException {
    switch (jj_ntk == -1 ? jj_ntk_f() : jj_ntk) {
    case K_NOT:{
      jj_consume_token(K_NOT);
      break;
      }
    default:
      jj_la1[15] = jj_gen;
      ;
    }
    jj_consume_token(K_BETWEEN);
    SqlSimpleExpression();
    jj_consume_token(K_AND);
    SqlSimpleExpression();
}

  final public void SqlLikeClause() throws ParseException {
    switch (jj_ntk == -1 ? jj_ntk_f() : jj_ntk) {
    case K_NOT:{
      jj_consume_token(K_NOT);
      break;
      }
    default:
      jj_la1[16] = jj_gen;
      ;
    }
    jj_consume_token(K_LIKE);
    SqlSimpleExpression();
}

  final public void IsNullClause() throws ParseException {
    jj_consume_token(K_IS);
    switch (jj_ntk == -1 ? jj_ntk_f() : jj_ntk) {
    case K_NOT:{
      jj_consume_token(K_NOT);
      break;
      }
    default:
      jj_la1[17] = jj_gen;
      ;
    }
    jj_consume_token(K_NULL);
}

  final public void SqlSimpleExpression() throws ParseException {
    SqlMultiplicativeExpression();
    label_5:
    while (true) {
      switch (jj_ntk == -1 ? jj_ntk_f() : jj_ntk) {
      case 80:
      case 81:
      case 82:{
        break;
        }
      default:
        jj_la1[18] = jj_gen;
        break label_5;
      }
      switch (jj_ntk == -1 ? jj_ntk_f() : jj_ntk) {
      case 80:{
        jj_consume_token(80);
        break;
        }
      case 81:{
        jj_consume_token(81);
        break;
        }
      case 82:{
        jj_consume_token(82);
        break;
        }
      default:
        jj_la1[19] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      SqlMultiplicativeExpression();
pop(ExpressionNode.FUNCTION, token.image, token.beginColumn, 2);
    }
}

  final public void SqlMultiplicativeExpression() throws ParseException {
    SqlUnaryExpression();
    label_6:
    while (true) {
      switch (jj_ntk == -1 ? jj_ntk_f() : jj_ntk) {
      case 83:
      case 84:{
        break;
        }
      default:
        jj_la1[20] = jj_gen;
        break label_6;
      }
      switch (jj_ntk == -1 ? jj_ntk_f() : jj_ntk) {
      case 83:{
        jj_consume_token(83);
        break;
        }
      case 84:{
        jj_consume_token(84);
        break;
        }
      default:
        jj_la1[21] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      SqlUnaryExpression();
pop(ExpressionNode.FUNCTION, token.image, token.beginColumn, 2);
    }
}

  final public void SqlUnaryExpression() throws ParseException {boolean hasMinus = false;
    switch (jj_ntk == -1 ? jj_ntk_f() : jj_ntk) {
    case 80:
    case 81:{
      switch (jj_ntk == -1 ? jj_ntk_f() : jj_ntk) {
      case 80:{
        jj_consume_token(80);
        break;
        }
      case 81:{
        jj_consume_token(81);
hasMinus = true;
        break;
        }
      default:
        jj_la1[22] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      SqlPrimaryExpression(hasMinus);
      break;
      }
    case K_CASE:
    case K_CAST:
    case K_NULL:
    case S_NUMBER:
    case S_IDENTIFIER:
    case S_BIND:
    case S_CHAR_LITERAL:
    case S_QUOTED_IDENTIFIER:
    case 66:
    case 76:{
      SqlPrimaryExpression(false);
      break;
      }
    default:
      jj_la1[23] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
}

  final public void SqlPrimaryExpression(boolean hasMinus) throws ParseException {
    switch (jj_ntk == -1 ? jj_ntk_f() : jj_ntk) {
    case S_NUMBER:{
      jj_consume_token(S_NUMBER);
push(ExpressionNode.LITERAL, token);
      break;
      }
    case S_CHAR_LITERAL:{
      jj_consume_token(S_CHAR_LITERAL);
push(ExpressionNode.LITERAL, token);
      break;
      }
    case K_NULL:{
      jj_consume_token(K_NULL);
push(ExpressionNode.LITERAL, token);
      break;
      }
    case K_CASE:{
      SqlCaseExpression();
      break;
      }
    case 76:{
      jj_consume_token(76);
      if (jj_2_5(3)) {
        SelectStatement();
      } else {
        switch (jj_ntk == -1 ? jj_ntk_f() : jj_ntk) {
        case K_CASE:
        case K_CAST:
        case K_NOT:
        case K_NULL:
        case S_NUMBER:
        case S_IDENTIFIER:
        case S_BIND:
        case S_CHAR_LITERAL:
        case S_QUOTED_IDENTIFIER:
        case 66:
        case 76:
        case 80:
        case 81:{
          SqlExpression();
          break;
          }
        default:
          jj_la1[24] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
      jj_consume_token(78);
      break;
      }
    case S_BIND:
    case 66:{
      BindVariable();
push(ExpressionNode.BIND_VARIABLE, token);
      break;
      }
    default:
      jj_la1[25] = jj_gen;
      if (jj_2_6(2)) {
        SqlCastExpression();
      } else if (jj_2_7(2147483647)) {
        IntervalExpression();
      } else if (jj_2_8(2147483647)) {
        FunctionCall();
      } else {
        switch (jj_ntk == -1 ? jj_ntk_f() : jj_ntk) {
        case S_IDENTIFIER:
        case S_QUOTED_IDENTIFIER:{
          ObjectReference();
          break;
          }
        default:
          jj_la1[26] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
    }
}

  final public void SqlCaseExpression() throws ParseException {int paramCount = 0;
    jj_consume_token(K_CASE);
    switch (jj_ntk == -1 ? jj_ntk_f() : jj_ntk) {
    case K_CASE:
    case K_CAST:
    case K_NULL:
    case S_NUMBER:
    case S_IDENTIFIER:
    case S_BIND:
    case S_CHAR_LITERAL:
    case S_QUOTED_IDENTIFIER:
    case 66:
    case 76:
    case 80:
    case 81:{
      SqlSimpleExpression();
paramCount = 1;
      label_7:
      while (true) {
        switch (jj_ntk == -1 ? jj_ntk_f() : jj_ntk) {
        case K_WHEN:{
          break;
          }
        default:
          jj_la1[27] = jj_gen;
          break label_7;
        }
        jj_consume_token(K_WHEN);
        SqlSimpleExpression();
        jj_consume_token(K_THEN);
        SqlSimpleExpression();
paramCount+=2;
      }
      break;
      }
    default:
      jj_la1[29] = jj_gen;
      label_8:
      while (true) {
        switch (jj_ntk == -1 ? jj_ntk_f() : jj_ntk) {
        case K_WHEN:{
          break;
          }
        default:
          jj_la1[28] = jj_gen;
          break label_8;
        }
        jj_consume_token(K_WHEN);
        SqlExpression();
        jj_consume_token(K_THEN);
        SqlSimpleExpression();
paramCount+=2;
      }
    }
    switch (jj_ntk == -1 ? jj_ntk_f() : jj_ntk) {
    case K_ELSE:{
      jj_consume_token(K_ELSE);
      SqlSimpleExpression();
paramCount++;
      break;
      }
    default:
      jj_la1[30] = jj_gen;
      ;
    }
    jj_consume_token(K_END);
pop(ExpressionNode.FUNCTION, "CASE", token.beginColumn, paramCount);
}

  final public void SqlCastExpression() throws ParseException {
    jj_consume_token(K_CAST);
    jj_consume_token(76);
    SqlExpression();
    jj_consume_token(K_AS);
    BasicDataTypeDefinition();
    jj_consume_token(78);
pop(ExpressionNode.FUNCTION, "CAST", token.beginColumn, 2);
}

  final public void TableColumn() throws ParseException {
    ObjectReference();
}

  final public void ObjectName() throws ParseException {
    switch (jj_ntk == -1 ? jj_ntk_f() : jj_ntk) {
    case S_IDENTIFIER:{
      jj_consume_token(S_IDENTIFIER);
push(ExpressionNode.LITERAL, token);
      break;
      }
    case S_QUOTED_IDENTIFIER:{
      jj_consume_token(S_QUOTED_IDENTIFIER);
push(ExpressionNode.LITERAL, token.image.subSequence(1, token.image.length() - 1), token.beginColumn);
      break;
      }
    default:
      jj_la1[31] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
}

  final public CharSequence TNSName() throws ParseException {StringBuilder name = new StringBuilder();
    jj_consume_token(S_IDENTIFIER);
name.append(token.image);
    label_9:
    while (true) {
      switch (jj_ntk == -1 ? jj_ntk_f() : jj_ntk) {
      case 85:{
        break;
        }
      default:
        jj_la1[32] = jj_gen;
        break label_9;
      }
      jj_consume_token(85);
      jj_consume_token(S_IDENTIFIER);
name.append(".").append(token.image);
    }
{if ("" != null) return name.toString();}
    throw new IllegalStateException ("Missing return statement in function");
}

  final public void Relop() throws ParseException {
    switch (jj_ntk == -1 ? jj_ntk_f() : jj_ntk) {
    case 86:{
      jj_consume_token(86);
      break;
      }
    case 87:{
      jj_consume_token(87);
      jj_consume_token(86);
      break;
      }
    case 88:{
      jj_consume_token(88);
      break;
      }
    default:
      jj_la1[33] = jj_gen;
      if (jj_2_9(2)) {
        jj_consume_token(89);
        jj_consume_token(86);
      } else {
        switch (jj_ntk == -1 ? jj_ntk_f() : jj_ntk) {
        case 89:{
          jj_consume_token(89);
          break;
          }
        default:
          jj_la1[34] = jj_gen;
          if (jj_2_10(2)) {
            jj_consume_token(90);
            jj_consume_token(89);
          } else if (jj_2_11(2)) {
            jj_consume_token(90);
            jj_consume_token(86);
          } else {
            switch (jj_ntk == -1 ? jj_ntk_f() : jj_ntk) {
            case 90:{
              jj_consume_token(90);
              break;
              }
            default:
              jj_la1[35] = jj_gen;
              jj_consume_token(-1);
              throw new ParseException();
            }
          }
        }
      }
    }
}

  final public void TableName() throws ParseException {
    ObjectName();
}

  final public void ParameterList() throws ParseException {
    Parameter();
    label_10:
    while (true) {
      switch (jj_ntk == -1 ? jj_ntk_f() : jj_ntk) {
      case 77:{
        break;
        }
      default:
        jj_la1[36] = jj_gen;
        break label_10;
      }
      jj_consume_token(77);
      Parameter();
    }
}

  final public void NumOrID() throws ParseException {
    switch (jj_ntk == -1 ? jj_ntk_f() : jj_ntk) {
    case S_IDENTIFIER:{
      jj_consume_token(S_IDENTIFIER);
      break;
      }
    case S_NUMBER:
    case 80:
    case 81:{
      switch (jj_ntk == -1 ? jj_ntk_f() : jj_ntk) {
      case 80:
      case 81:{
        switch (jj_ntk == -1 ? jj_ntk_f() : jj_ntk) {
        case 80:{
          jj_consume_token(80);
          break;
          }
        case 81:{
          jj_consume_token(81);
          break;
          }
        default:
          jj_la1[37] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
        break;
        }
      default:
        jj_la1[38] = jj_gen;
        ;
      }
      jj_consume_token(S_NUMBER);
      break;
      }
    default:
      jj_la1[39] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
}

  final public void Parameter() throws ParseException {
    jj_consume_token(S_IDENTIFIER);
    switch (jj_ntk == -1 ? jj_ntk_f() : jj_ntk) {
    case K_BOOLEAN:
    case K_CHAR:
    case K_DATE:
    case K_DOUBLE:
    case K_FLOAT:
    case K_IN:
    case K_STRING:
    case 67:
    case 68:
    case 69:
    case 70:
    case 71:
    case 72:
    case 73:
    case 74:
    case 91:{
      switch (jj_ntk == -1 ? jj_ntk_f() : jj_ntk) {
      case K_IN:{
        jj_consume_token(K_IN);
        break;
        }
      default:
        jj_la1[40] = jj_gen;
        ;
      }
      switch (jj_ntk == -1 ? jj_ntk_f() : jj_ntk) {
      case 91:{
        jj_consume_token(91);
        break;
        }
      default:
        jj_la1[41] = jj_gen;
        ;
      }
      BasicDataTypeDefinition();
      switch (jj_ntk == -1 ? jj_ntk_f() : jj_ntk) {
      case 92:
      case 93:{
        switch (jj_ntk == -1 ? jj_ntk_f() : jj_ntk) {
        case 92:{
          jj_consume_token(92);
          break;
          }
        case 93:{
          jj_consume_token(93);
          break;
          }
        default:
          jj_la1[42] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
        SqlExpression();
        break;
        }
      default:
        jj_la1[43] = jj_gen;
        ;
      }
      break;
      }
    default:
      jj_la1[44] = jj_gen;
      ;
    }
}

  final public void Arguments() throws ParseException {
    Argument();
    label_11:
    while (true) {
      switch (jj_ntk == -1 ? jj_ntk_f() : jj_ntk) {
      case 77:{
        break;
        }
      default:
        jj_la1[45] = jj_gen;
        break label_11;
      }
      jj_consume_token(77);
      Argument();
    }
}

  final public void Argument() throws ParseException {
    if (jj_2_12(2)) {
      jj_consume_token(S_IDENTIFIER);
      jj_consume_token(94);
    } else {
      ;
    }
    SqlExpression();
}

  final public void SelectStatement() throws ParseException {
    SelectWithoutOrder();
    switch (jj_ntk == -1 ? jj_ntk_f() : jj_ntk) {
    case K_ORDER:{
      OrderByClause();
      break;
      }
    default:
      jj_la1[46] = jj_gen;
      ;
    }
}

  final public void SelectWithoutOrder() throws ParseException {String operation;
    SelectSet();
    label_12:
    while (true) {
      switch (jj_ntk == -1 ? jj_ntk_f() : jj_ntk) {
      case K_UNION:
      case 95:
      case 96:{
        break;
        }
      default:
        jj_la1[47] = jj_gen;
        break label_12;
      }
      switch (jj_ntk == -1 ? jj_ntk_f() : jj_ntk) {
      case K_UNION:{
        jj_consume_token(K_UNION);
operation = "UNION";
        switch (jj_ntk == -1 ? jj_ntk_f() : jj_ntk) {
        case K_ALL:{
          jj_consume_token(K_ALL);
operation = "UNION ALL";
          break;
          }
        default:
          jj_la1[48] = jj_gen;
          ;
        }
        break;
        }
      case 95:{
        jj_consume_token(95);
operation = "INTERSECT";
        break;
        }
      case 96:{
        jj_consume_token(96);
operation = "MINUS";
        break;
        }
      default:
        jj_la1[49] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      SelectSet();
pop(ExpressionNode.SET_OPERATION,operation, token.beginColumn, 2);
    }
}

  final public void SelectSet() throws ParseException {
    switch (jj_ntk == -1 ? jj_ntk_f() : jj_ntk) {
    case K_SELECT:{
      Select();
      break;
      }
    case 76:{
      jj_consume_token(76);
      SubQuery();
      jj_consume_token(78);
      break;
      }
    default:
      jj_la1[50] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
}

  final public void Select() throws ParseException {String modifier = null;
    jj_consume_token(K_SELECT);
    switch (jj_ntk == -1 ? jj_ntk_f() : jj_ntk) {
    case K_ALL:
    case K_DISTINCT:
    case 97:{
      switch (jj_ntk == -1 ? jj_ntk_f() : jj_ntk) {
      case K_ALL:{
        jj_consume_token(K_ALL);
        break;
        }
      case K_DISTINCT:{
        jj_consume_token(K_DISTINCT);
        break;
        }
      case 97:{
        jj_consume_token(97);
modifier = token.image;
        break;
        }
      default:
        jj_la1[51] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      break;
      }
    default:
      jj_la1[52] = jj_gen;
      ;
    }
    SelectList();
popSelect(modifier);
    FromClause();
popFrom();
    switch (jj_ntk == -1 ? jj_ntk_f() : jj_ntk) {
    case K_WHERE:{
      WhereClause();
popWhere();
      break;
      }
    default:
      jj_la1[53] = jj_gen;
      ;
    }
}

  final public void SelectList() throws ParseException {
    switch (jj_ntk == -1 ? jj_ntk_f() : jj_ntk) {
    case 83:{
      jj_consume_token(83);
      break;
      }
    case K_CASE:
    case K_CAST:
    case K_NULL:
    case S_NUMBER:
    case S_IDENTIFIER:
    case S_BIND:
    case S_CHAR_LITERAL:
    case S_QUOTED_IDENTIFIER:
    case 66:
    case 76:
    case 80:
    case 81:{
      SelectItem();
      label_13:
      while (true) {
        switch (jj_ntk == -1 ? jj_ntk_f() : jj_ntk) {
        case 77:{
          break;
          }
        default:
          jj_la1[54] = jj_gen;
          break label_13;
        }
        jj_consume_token(77);
        SelectItem();
      }
      break;
      }
    default:
      jj_la1[55] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
}

  final public void SelectItem() throws ParseException {
    if (jj_2_13(2)) {
      ObjectName();
      jj_consume_token(98);
    } else if (jj_2_14(4)) {
      ObjectName();
      jj_consume_token(85);
      ObjectName();
      jj_consume_token(98);
    } else {
      switch (jj_ntk == -1 ? jj_ntk_f() : jj_ntk) {
      case K_CASE:
      case K_CAST:
      case K_NULL:
      case S_NUMBER:
      case S_IDENTIFIER:
      case S_BIND:
      case S_CHAR_LITERAL:
      case S_QUOTED_IDENTIFIER:
      case 66:
      case 76:
      case 80:
      case 81:{
        SqlSimpleExpression();
        break;
        }
      default:
        jj_la1[56] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
    switch (jj_ntk == -1 ? jj_ntk_f() : jj_ntk) {
    case K_AS:
    case K_WHEN:
    case S_IDENTIFIER:
    case S_QUOTED_IDENTIFIER:
    case 99:{
      switch (jj_ntk == -1 ? jj_ntk_f() : jj_ntk) {
      case K_AS:{
        jj_consume_token(K_AS);
        break;
        }
      default:
        jj_la1[57] = jj_gen;
        ;
      }
      SelectItemAlias();
      break;
      }
    default:
      jj_la1[58] = jj_gen;
      ;
    }
}

  final public void SelectItemAlias() throws ParseException {
    switch (jj_ntk == -1 ? jj_ntk_f() : jj_ntk) {
    case S_IDENTIFIER:
    case S_QUOTED_IDENTIFIER:{
      ObjectName();
      break;
      }
    case 99:{
      jj_consume_token(99);
      break;
      }
    case K_WHEN:{
      jj_consume_token(K_WHEN);
      break;
      }
    default:
      jj_la1[59] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
}

  final public void AnalyticFunction() throws ParseException {
    FunctionCall();
    switch (jj_ntk == -1 ? jj_ntk_f() : jj_ntk) {
    case 100:{
      jj_consume_token(100);
      jj_consume_token(76);
      AnalyticClause();
      jj_consume_token(78);
      break;
      }
    default:
      jj_la1[60] = jj_gen;
      ;
    }
}

  final public void AnalyticClause() throws ParseException {
    switch (jj_ntk == -1 ? jj_ntk_f() : jj_ntk) {
    case K_PARTITION:{
      QueryPartitionClause();
      break;
      }
    default:
      jj_la1[61] = jj_gen;
      ;
    }
    switch (jj_ntk == -1 ? jj_ntk_f() : jj_ntk) {
    case K_ORDER:{
      OrderByClause();
      switch (jj_ntk == -1 ? jj_ntk_f() : jj_ntk) {
      case 101:
      case 102:{
        WindowingClause();
        break;
        }
      default:
        jj_la1[62] = jj_gen;
        ;
      }
      break;
      }
    default:
      jj_la1[63] = jj_gen;
      ;
    }
}

  final public void QueryPartitionClause() throws ParseException {
    jj_consume_token(K_PARTITION);
    jj_consume_token(K_BY);
    SqlExpression();
    label_14:
    while (true) {
      switch (jj_ntk == -1 ? jj_ntk_f() : jj_ntk) {
      case 77:{
        break;
        }
      default:
        jj_la1[64] = jj_gen;
        break label_14;
      }
      jj_consume_token(77);
      SqlExpression();
    }
}

  final public void WindowingClause() throws ParseException {
    switch (jj_ntk == -1 ? jj_ntk_f() : jj_ntk) {
    case 101:{
      jj_consume_token(101);
      break;
      }
    case 102:{
      jj_consume_token(102);
      break;
      }
    default:
      jj_la1[65] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    switch (jj_ntk == -1 ? jj_ntk_f() : jj_ntk) {
    case 103:{
      jj_consume_token(103);
      jj_consume_token(104);
      break;
      }
    case K_CASE:
    case K_CAST:
    case K_NULL:
    case S_NUMBER:
    case S_IDENTIFIER:
    case S_BIND:
    case S_CHAR_LITERAL:
    case S_QUOTED_IDENTIFIER:
    case 66:
    case 76:
    case 80:
    case 81:{
      SqlSimpleExpression();
      ID("PRECEDING");
      break;
      }
    case K_BETWEEN:{
      jj_consume_token(K_BETWEEN);
      switch (jj_ntk == -1 ? jj_ntk_f() : jj_ntk) {
      case 103:{
        jj_consume_token(103);
        jj_consume_token(104);
        break;
        }
      case K_CASE:
      case K_CAST:
      case K_NULL:
      case S_NUMBER:
      case S_IDENTIFIER:
      case S_BIND:
      case S_CHAR_LITERAL:
      case S_QUOTED_IDENTIFIER:
      case 66:
      case 76:
      case 80:
      case 81:{
        SqlSimpleExpression();
        ID("PRECEDING|FOLLOWING");
        break;
        }
      default:
        jj_la1[66] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      jj_consume_token(K_AND);
      switch (jj_ntk == -1 ? jj_ntk_f() : jj_ntk) {
      case 103:{
        jj_consume_token(103);
        jj_consume_token(104);
        break;
        }
      case K_CASE:
      case K_CAST:
      case K_NULL:
      case S_NUMBER:
      case S_IDENTIFIER:
      case S_BIND:
      case S_CHAR_LITERAL:
      case S_QUOTED_IDENTIFIER:
      case 66:
      case 76:
      case 80:
      case 81:{
        SqlSimpleExpression();
        ID("PRECEDING|FOLLOWING");
        break;
        }
      default:
        jj_la1[67] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      break;
      }
    default:
      jj_la1[68] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
}

  final public void IntoClause() throws ParseException {
    jj_consume_token(K_INTO);
    DataItem();
    label_15:
    while (true) {
      switch (jj_ntk == -1 ? jj_ntk_f() : jj_ntk) {
      case 77:{
        break;
        }
      default:
        jj_la1[69] = jj_gen;
        break label_15;
      }
      jj_consume_token(77);
      DataItem();
    }
}

  final public void DataItem() throws ParseException {
    switch (jj_ntk == -1 ? jj_ntk_f() : jj_ntk) {
    case S_IDENTIFIER:{
      jj_consume_token(S_IDENTIFIER);
      switch (jj_ntk == -1 ? jj_ntk_f() : jj_ntk) {
      case 85:{
        jj_consume_token(85);
        jj_consume_token(S_IDENTIFIER);
        break;
        }
      default:
        jj_la1[70] = jj_gen;
        ;
      }
      break;
      }
    case S_BIND:
    case 66:{
      BindVariable();
      break;
      }
    default:
      jj_la1[71] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    switch (jj_ntk == -1 ? jj_ntk_f() : jj_ntk) {
    case 76:{
      jj_consume_token(76);
      SqlSimpleExpression();
      jj_consume_token(78);
      break;
      }
    default:
      jj_la1[72] = jj_gen;
      ;
    }
}

  final public void FromClause() throws ParseException {
    jj_consume_token(K_FROM);
    TableReference();
    label_16:
    while (true) {
      switch (jj_ntk == -1 ? jj_ntk_f() : jj_ntk) {
      case 77:{
        break;
        }
      default:
        jj_la1[73] = jj_gen;
        break label_16;
      }
      jj_consume_token(77);
      TableReference();
    }
}

  final public void TableReference() throws ParseException {
    switch (jj_ntk == -1 ? jj_ntk_f() : jj_ntk) {
    case 105:{
      jj_consume_token(105);
      jj_consume_token(76);
      QueryTableExpression();
      jj_consume_token(78);
      break;
      }
    case K_TABLE:
    case S_IDENTIFIER:
    case S_BIND:
    case S_QUOTED_IDENTIFIER:
    case 66:
    case 76:{
      QueryTableExpression();
      break;
      }
    default:
      jj_la1[74] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
}

  final public void QueryTableExpression() throws ParseException {
    switch (jj_ntk == -1 ? jj_ntk_f() : jj_ntk) {
    case S_IDENTIFIER:
    case S_QUOTED_IDENTIFIER:{
      TableName();
      break;
      }
    case K_TABLE:{
      TableCollectionExpression();
      break;
      }
    default:
      jj_la1[75] = jj_gen;
      if (jj_2_15(3)) {
        jj_consume_token(76);
        SubQuery();
        jj_consume_token(78);
      } else {
        switch (jj_ntk == -1 ? jj_ntk_f() : jj_ntk) {
        case 76:{
          jj_consume_token(76);
          TableReference();
          jj_consume_token(78);
          break;
          }
        case S_BIND:
        case 66:{
          BindVariable();
          break;
          }
        default:
          jj_la1[76] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
    }
    switch (jj_ntk == -1 ? jj_ntk_f() : jj_ntk) {
    case 106:{
      jj_consume_token(106);
      jj_consume_token(76);
      jj_consume_token(S_NUMBER);
      jj_consume_token(77);
      jj_consume_token(S_IDENTIFIER);
      jj_consume_token(77);
      jj_consume_token(S_IDENTIFIER);
      jj_consume_token(78);
      break;
      }
    default:
      jj_la1[77] = jj_gen;
      ;
    }
    switch (jj_ntk == -1 ? jj_ntk_f() : jj_ntk) {
    case K_SAMPLE:{
      jj_consume_token(K_SAMPLE);
      switch (jj_ntk == -1 ? jj_ntk_f() : jj_ntk) {
      case S_IDENTIFIER:{
        ID("BLOCK");
        break;
        }
      default:
        jj_la1[78] = jj_gen;
        ;
      }
      jj_consume_token(76);
      jj_consume_token(S_NUMBER);
      jj_consume_token(78);
      break;
      }
    default:
      jj_la1[79] = jj_gen;
      ;
    }
    switch (jj_ntk == -1 ? jj_ntk_f() : jj_ntk) {
    case S_IDENTIFIER:
    case S_QUOTED_IDENTIFIER:{
      ObjectName();
      break;
      }
    default:
      jj_la1[80] = jj_gen;
      ;
    }
    label_17:
    while (true) {
      switch (jj_ntk == -1 ? jj_ntk_f() : jj_ntk) {
      case K_FULL:
      case K_INNER:
      case K_LEFT:
      case 108:{
        break;
        }
      default:
        jj_la1[81] = jj_gen;
        break label_17;
      }
      Join();
    }
}

  final public void TableCollectionExpression() throws ParseException {
    jj_consume_token(K_TABLE);
    jj_consume_token(76);
    SqlSimpleExpression();
    jj_consume_token(78);
    switch (jj_ntk == -1 ? jj_ntk_f() : jj_ntk) {
    case 76:{
      jj_consume_token(76);
      jj_consume_token(80);
      jj_consume_token(78);
      break;
      }
    default:
      jj_la1[82] = jj_gen;
      ;
    }
}

  final public void Join() throws ParseException {
    JoinType();
    ID("JOIN");
    TableReference();
    jj_consume_token(107);
    SqlExpression();
}

  final public void JoinType() throws ParseException {
    switch (jj_ntk == -1 ? jj_ntk_f() : jj_ntk) {
    case K_INNER:{
      jj_consume_token(K_INNER);
      break;
      }
    case K_FULL:
    case K_LEFT:
    case 108:{
      switch (jj_ntk == -1 ? jj_ntk_f() : jj_ntk) {
      case K_LEFT:{
        jj_consume_token(K_LEFT);
        break;
        }
      case 108:{
        jj_consume_token(108);
        break;
        }
      case K_FULL:{
        jj_consume_token(K_FULL);
        break;
        }
      default:
        jj_la1[83] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      ID("OUTER");
      break;
      }
    default:
      jj_la1[84] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
}

  final public void ColumnName() throws ParseException {
    jj_consume_token(S_IDENTIFIER);
}

  final public void WhereClause() throws ParseException {
    jj_consume_token(K_WHERE);
    SqlExpression();
}

  final public void OrderByClause() throws ParseException {
    jj_consume_token(K_ORDER);
    jj_consume_token(K_BY);
    OrderByExpression();
    label_18:
    while (true) {
      switch (jj_ntk == -1 ? jj_ntk_f() : jj_ntk) {
      case 77:{
        break;
        }
      default:
        jj_la1[85] = jj_gen;
        break label_18;
      }
      jj_consume_token(77);
      OrderByExpression();
    }
}

  final public void OrderByExpression() throws ParseException {
    SqlSimpleExpression();
    switch (jj_ntk == -1 ? jj_ntk_f() : jj_ntk) {
    case K_ASC:
    case K_DESC:{
      switch (jj_ntk == -1 ? jj_ntk_f() : jj_ntk) {
      case K_ASC:{
        jj_consume_token(K_ASC);
        break;
        }
      case K_DESC:{
        jj_consume_token(K_DESC);
        break;
        }
      default:
        jj_la1[86] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      break;
      }
    default:
      jj_la1[87] = jj_gen;
      ;
    }
    switch (jj_ntk == -1 ? jj_ntk_f() : jj_ntk) {
    case 109:{
      jj_consume_token(109);
      ID("LAST");
      break;
      }
    default:
      jj_la1[88] = jj_gen;
      ;
    }
}

  final public void ExistsClause() throws ParseException {
    switch (jj_ntk == -1 ? jj_ntk_f() : jj_ntk) {
    case K_NOT:{
      jj_consume_token(K_NOT);
      break;
      }
    default:
      jj_la1[89] = jj_gen;
      ;
    }
    jj_consume_token(110);
    jj_consume_token(76);
    SubQuery();
    jj_consume_token(78);
}

  final public void IntervalExpression() throws ParseException {
    ID("INTERVAL");
    SqlSimpleExpression();
    if ("DAY".equalsIgnoreCase(getToken(1).image)) {
      ID("DAY");
      switch (jj_ntk == -1 ? jj_ntk_f() : jj_ntk) {
      case 76:{
        jj_consume_token(76);
        jj_consume_token(S_NUMBER);
        jj_consume_token(78);
        break;
        }
      default:
        jj_la1[90] = jj_gen;
        ;
      }
      jj_consume_token(111);
      ID("SECOND");
      switch (jj_ntk == -1 ? jj_ntk_f() : jj_ntk) {
      case 76:{
        jj_consume_token(76);
        jj_consume_token(S_NUMBER);
        jj_consume_token(78);
        break;
        }
      default:
        jj_la1[91] = jj_gen;
        ;
      }
    } else {
      switch (jj_ntk == -1 ? jj_ntk_f() : jj_ntk) {
      case S_IDENTIFIER:{
        ID("YEAR");
        switch (jj_ntk == -1 ? jj_ntk_f() : jj_ntk) {
        case 76:{
          jj_consume_token(76);
          jj_consume_token(S_NUMBER);
          jj_consume_token(78);
          break;
          }
        default:
          jj_la1[92] = jj_gen;
          ;
        }
        jj_consume_token(111);
        ID("MONTH");
        switch (jj_ntk == -1 ? jj_ntk_f() : jj_ntk) {
        case 76:{
          jj_consume_token(76);
          jj_consume_token(S_NUMBER);
          jj_consume_token(78);
          break;
          }
        default:
          jj_la1[93] = jj_gen;
          ;
        }
        break;
        }
      default:
        jj_la1[94] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
}

  final public void FunctionCall() throws ParseException {
    FunctionReference();
}

  final public void FunctionReference() throws ParseException {
    ObjectReference();
}

  final public void FunctionArgumentList() throws ParseException {
    FunctionArgument();
    label_19:
    while (true) {
      switch (jj_ntk == -1 ? jj_ntk_f() : jj_ntk) {
      case 77:{
        break;
        }
      default:
        jj_la1[95] = jj_gen;
        break label_19;
      }
      jj_consume_token(77);
      FunctionArgument();
    }
}

  final public void FunctionArgument() throws ParseException {
    if (jj_2_16(2)) {
      jj_consume_token(S_IDENTIFIER);
      jj_consume_token(94);
    } else {
      ;
    }
    SqlExpression();
}

  final public void TrimArguments() throws ParseException {
    jj_consume_token(76);
    if (getToken(1).image.matches("(?i)LEADING|TRAILING|BOTH")) {
      jj_consume_token(S_IDENTIFIER);
      switch (jj_ntk == -1 ? jj_ntk_f() : jj_ntk) {
      case K_CASE:
      case K_CAST:
      case K_NULL:
      case S_NUMBER:
      case S_IDENTIFIER:
      case S_BIND:
      case S_CHAR_LITERAL:
      case S_QUOTED_IDENTIFIER:
      case 66:
      case 76:
      case 80:
      case 81:{
        SqlSimpleExpression();
        break;
        }
      default:
        jj_la1[96] = jj_gen;
        ;
      }
      jj_consume_token(K_FROM);
      SqlSimpleExpression();
    } else {
      switch (jj_ntk == -1 ? jj_ntk_f() : jj_ntk) {
      case K_CASE:
      case K_CAST:
      case K_NULL:
      case S_NUMBER:
      case S_IDENTIFIER:
      case S_BIND:
      case S_CHAR_LITERAL:
      case S_QUOTED_IDENTIFIER:
      case 66:
      case 76:
      case 80:
      case 81:{
        SqlSimpleExpression();
        switch (jj_ntk == -1 ? jj_ntk_f() : jj_ntk) {
        case K_FROM:{
          jj_consume_token(K_FROM);
          SqlSimpleExpression();
          break;
          }
        default:
          jj_la1[97] = jj_gen;
          ;
        }
        break;
        }
      default:
        jj_la1[98] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
    jj_consume_token(78);
}

  final public void DatetimeField() throws ParseException {
    jj_consume_token(S_IDENTIFIER);
}

  final public void ObjectReference() throws ParseException {int paramCount = 1;
    String literal0 = null;
    ObjectName();
literal0 = token.image;
    switch (jj_ntk == -1 ? jj_ntk_f() : jj_ntk) {
    case 85:{
      jj_consume_token(85);
      ObjectName();
literal0 += "." + token.image; paramCount++;
      switch (jj_ntk == -1 ? jj_ntk_f() : jj_ntk) {
      case 85:{
        jj_consume_token(85);
        ObjectName();
literal0 += "." + token.image; paramCount++;
        break;
        }
      default:
        jj_la1[99] = jj_gen;
        ;
      }
      break;
      }
    default:
      jj_la1[100] = jj_gen;
      ;
    }
if (paramCount == 2) {
        replace(ExpressionNode.LITERAL, literal0, token.beginColumn, paramCount);
    }
}

  final public void OuterJoinExpression() throws ParseException {
    TableColumn();
    jj_consume_token(76);
    jj_consume_token(80);
    jj_consume_token(78);
}

  final public void SubQuery() throws ParseException {
    SelectStatement();
}

/** Expect an <S_IDENTIFIER> with the given value. */
  final public void ID(String id) throws ParseException {
    jj_consume_token(S_IDENTIFIER);
if (!token.image.matches("(?i)" + id)) {
            throw new ParseException("Encountered " + token.image
                + " at line " + token.beginLine + ", column " + token.beginColumn + "."
                + "\nWas expecting: " + id);
        }
}

  private boolean jj_2_1(int xla)
 {
    jj_la = xla;
    jj_scanpos = token;
    jj_lastpos = token;
    try { return (!jj_3_1()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(0, xla); }
  }

  private boolean jj_2_2(int xla)
 {
    jj_la = xla;
    jj_scanpos = token;
    jj_lastpos = token;
    try { return (!jj_3_2()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(1, xla); }
  }

  private boolean jj_2_3(int xla)
 {
    jj_la = xla;
    jj_scanpos = token;
    jj_lastpos = token;
    try { return (!jj_3_3()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(2, xla); }
  }

  private boolean jj_2_4(int xla)
 {
    jj_la = xla;
    jj_scanpos = token;
    jj_lastpos = token;
    try { return (!jj_3_4()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(3, xla); }
  }

  private boolean jj_2_5(int xla)
 {
    jj_la = xla;
    jj_scanpos = token;
    jj_lastpos = token;
    try { return (!jj_3_5()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(4, xla); }
  }

  private boolean jj_2_6(int xla)
 {
    jj_la = xla;
    jj_scanpos = token;
    jj_lastpos = token;
    try { return (!jj_3_6()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(5, xla); }
  }

  private boolean jj_2_7(int xla)
 {
    jj_la = xla;
    jj_scanpos = token;
    jj_lastpos = token;
    try { return (!jj_3_7()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(6, xla); }
  }

  private boolean jj_2_8(int xla)
 {
    jj_la = xla;
    jj_scanpos = token;
    jj_lastpos = token;
    try { return (!jj_3_8()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(7, xla); }
  }

  private boolean jj_2_9(int xla)
 {
    jj_la = xla;
    jj_scanpos = token;
    jj_lastpos = token;
    try { return (!jj_3_9()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(8, xla); }
  }

  private boolean jj_2_10(int xla)
 {
    jj_la = xla;
    jj_scanpos = token;
    jj_lastpos = token;
    try { return (!jj_3_10()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(9, xla); }
  }

  private boolean jj_2_11(int xla)
 {
    jj_la = xla;
    jj_scanpos = token;
    jj_lastpos = token;
    try { return (!jj_3_11()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(10, xla); }
  }

  private boolean jj_2_12(int xla)
 {
    jj_la = xla;
    jj_scanpos = token;
    jj_lastpos = token;
    try { return (!jj_3_12()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(11, xla); }
  }

  private boolean jj_2_13(int xla)
 {
    jj_la = xla;
    jj_scanpos = token;
    jj_lastpos = token;
    try { return (!jj_3_13()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(12, xla); }
  }

  private boolean jj_2_14(int xla)
 {
    jj_la = xla;
    jj_scanpos = token;
    jj_lastpos = token;
    try { return (!jj_3_14()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(13, xla); }
  }

  private boolean jj_2_15(int xla)
 {
    jj_la = xla;
    jj_scanpos = token;
    jj_lastpos = token;
    try { return (!jj_3_15()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(14, xla); }
  }

  private boolean jj_2_16(int xla)
 {
    jj_la = xla;
    jj_scanpos = token;
    jj_lastpos = token;
    try { return (!jj_3_16()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(15, xla); }
  }

  private boolean jj_3R_57()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(83)) {
    jj_scanpos = xsp;
    if (jj_3R_69()) return true;
    }
    return false;
  }

  private boolean jj_3_1()
 {
    if (jj_scan_token(76)) return true;
    if (jj_3R_20()) return true;
    return false;
  }

  private boolean jj_3R_102()
 {
    if (jj_scan_token(K_ALL)) return true;
    return false;
  }

  private boolean jj_3R_56()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(5)) {
    jj_scanpos = xsp;
    if (jj_scan_token(22)) {
    jj_scanpos = xsp;
    if (jj_3R_68()) return true;
    }
    }
    return false;
  }

  private boolean jj_3R_69()
 {
    if (jj_3R_73()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_74()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_73()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_13()) {
    jj_scanpos = xsp;
    if (jj_3_14()) {
    jj_scanpos = xsp;
    if (jj_3R_77()) return true;
    }
    }
    xsp = jj_scanpos;
    if (jj_3R_78()) jj_scanpos = xsp;
    return false;
  }

  private boolean jj_3_13()
 {
    if (jj_3R_28()) return true;
    if (jj_scan_token(98)) return true;
    return false;
  }

  private boolean jj_3_14()
 {
    if (jj_3R_28()) return true;
    if (jj_scan_token(85)) return true;
    if (jj_3R_28()) return true;
    if (jj_scan_token(98)) return true;
    return false;
  }

  private boolean jj_3R_77()
 {
    if (jj_3R_31()) return true;
    return false;
  }

  private boolean jj_3R_78()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(9)) jj_scanpos = xsp;
    if (jj_3R_84()) return true;
    return false;
  }

  private boolean jj_3R_82()
 {
    if (jj_3R_88()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_89()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_84()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_90()) {
    jj_scanpos = xsp;
    if (jj_scan_token(99)) {
    jj_scanpos = xsp;
    if (jj_scan_token(52)) return true;
    }
    }
    return false;
  }

  private boolean jj_3R_90()
 {
    if (jj_3R_28()) return true;
    return false;
  }

  private boolean jj_3R_74()
 {
    if (jj_scan_token(77)) return true;
    if (jj_3R_73()) return true;
    return false;
  }

  private boolean jj_3R_88()
 {
    if (jj_3R_93()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_94()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_68()
 {
    if (jj_scan_token(97)) return true;
    return false;
  }

  private boolean jj_3R_93()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_100()) jj_scanpos = xsp;
    if (jj_3R_101()) return true;
    return false;
  }

  private boolean jj_3R_100()
 {
    if (jj_scan_token(K_NOT)) return true;
    return false;
  }

  private boolean jj_3R_89()
 {
    if (jj_scan_token(K_OR)) return true;
    if (jj_3R_88()) return true;
    return false;
  }

  private boolean jj_3R_101()
 {
    if (jj_3R_31()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_105()) jj_scanpos = xsp;
    return false;
  }

  private boolean jj_3R_105()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_107()) {
    jj_scanpos = xsp;
    if (jj_3_2()) {
    jj_scanpos = xsp;
    if (jj_3_3()) {
    jj_scanpos = xsp;
    if (jj_3_4()) {
    jj_scanpos = xsp;
    if (jj_3R_108()) return true;
    }
    }
    }
    }
    return false;
  }

  private boolean jj_3R_107()
 {
    if (jj_3R_112()) return true;
    if (jj_3R_31()) return true;
    return false;
  }

  private boolean jj_3_2()
 {
    if (jj_3R_21()) return true;
    return false;
  }

  private boolean jj_3_3()
 {
    if (jj_3R_22()) return true;
    return false;
  }

  private boolean jj_3_4()
 {
    if (jj_3R_23()) return true;
    return false;
  }

  private boolean jj_3R_94()
 {
    if (jj_scan_token(K_AND)) return true;
    if (jj_3R_93()) return true;
    return false;
  }

  private boolean jj_3R_108()
 {
    if (jj_3R_113()) return true;
    return false;
  }

  private boolean jj_3R_117()
 {
    if (jj_3R_82()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_119()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_21()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(38)) jj_scanpos = xsp;
    if (jj_scan_token(K_IN)) return true;
    if (jj_scan_token(76)) return true;
    if (jj_3R_117()) return true;
    if (jj_scan_token(78)) return true;
    return false;
  }

  private boolean jj_3R_58()
 {
    if (jj_scan_token(K_FROM)) return true;
    if (jj_3R_109()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_110()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_22()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(38)) jj_scanpos = xsp;
    if (jj_scan_token(K_BETWEEN)) return true;
    if (jj_3R_31()) return true;
    if (jj_scan_token(K_AND)) return true;
    if (jj_3R_31()) return true;
    return false;
  }

  private boolean jj_3R_109()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_114()) {
    jj_scanpos = xsp;
    if (jj_3R_115()) return true;
    }
    return false;
  }

  private boolean jj_3R_114()
 {
    if (jj_scan_token(105)) return true;
    if (jj_scan_token(76)) return true;
    if (jj_3R_118()) return true;
    if (jj_scan_token(78)) return true;
    return false;
  }

  private boolean jj_3R_115()
 {
    if (jj_3R_118()) return true;
    return false;
  }

  private boolean jj_3R_119()
 {
    if (jj_scan_token(77)) return true;
    if (jj_3R_82()) return true;
    return false;
  }

  private boolean jj_3R_23()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(38)) jj_scanpos = xsp;
    if (jj_scan_token(K_LIKE)) return true;
    if (jj_3R_31()) return true;
    return false;
  }

  private boolean jj_3R_118()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_120()) {
    jj_scanpos = xsp;
    if (jj_3R_121()) {
    jj_scanpos = xsp;
    if (jj_3_15()) {
    jj_scanpos = xsp;
    if (jj_3R_122()) {
    jj_scanpos = xsp;
    if (jj_3R_123()) return true;
    }
    }
    }
    }
    xsp = jj_scanpos;
    if (jj_3R_124()) jj_scanpos = xsp;
    xsp = jj_scanpos;
    if (jj_3R_125()) jj_scanpos = xsp;
    xsp = jj_scanpos;
    if (jj_3R_126()) jj_scanpos = xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_127()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_113()
 {
    if (jj_scan_token(K_IS)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(38)) jj_scanpos = xsp;
    if (jj_scan_token(K_NULL)) return true;
    return false;
  }

  private boolean jj_3R_120()
 {
    if (jj_3R_128()) return true;
    return false;
  }

  private boolean jj_3R_121()
 {
    if (jj_3R_129()) return true;
    return false;
  }

  private boolean jj_3_15()
 {
    if (jj_scan_token(76)) return true;
    if (jj_3R_29()) return true;
    if (jj_scan_token(78)) return true;
    return false;
  }

  private boolean jj_3R_122()
 {
    if (jj_scan_token(76)) return true;
    if (jj_3R_109()) return true;
    if (jj_scan_token(78)) return true;
    return false;
  }

  private boolean jj_3R_31()
 {
    if (jj_3R_38()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_40()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_123()
 {
    if (jj_3R_71()) return true;
    return false;
  }

  private boolean jj_3R_124()
 {
    if (jj_scan_token(106)) return true;
    if (jj_scan_token(76)) return true;
    if (jj_scan_token(S_NUMBER)) return true;
    if (jj_scan_token(77)) return true;
    if (jj_scan_token(S_IDENTIFIER)) return true;
    if (jj_scan_token(77)) return true;
    if (jj_scan_token(S_IDENTIFIER)) return true;
    if (jj_scan_token(78)) return true;
    return false;
  }

  private boolean jj_3R_125()
 {
    if (jj_scan_token(K_SAMPLE)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_130()) jj_scanpos = xsp;
    if (jj_scan_token(76)) return true;
    if (jj_scan_token(S_NUMBER)) return true;
    if (jj_scan_token(78)) return true;
    return false;
  }

  private boolean jj_3R_126()
 {
    if (jj_3R_28()) return true;
    return false;
  }

  private boolean jj_3R_127()
 {
    if (jj_3R_131()) return true;
    return false;
  }

  private boolean jj_3R_110()
 {
    if (jj_scan_token(77)) return true;
    if (jj_3R_109()) return true;
    return false;
  }

  private boolean jj_3R_38()
 {
    if (jj_3R_46()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_49()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_129()
 {
    if (jj_scan_token(K_TABLE)) return true;
    if (jj_scan_token(76)) return true;
    if (jj_3R_31()) return true;
    if (jj_scan_token(78)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_132()) jj_scanpos = xsp;
    return false;
  }

  private boolean jj_3R_130()
 {
    if (jj_3R_33()) return true;
    return false;
  }

  private boolean jj_3R_46()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_51()) {
    jj_scanpos = xsp;
    if (jj_3R_52()) return true;
    }
    return false;
  }

  private boolean jj_3R_51()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(80)) {
    jj_scanpos = xsp;
    if (jj_3R_54()) return true;
    }
    if (jj_3R_55()) return true;
    return false;
  }

  private boolean jj_3R_131()
 {
    if (jj_3R_133()) return true;
    if (jj_3R_33()) return true;
    if (jj_3R_109()) return true;
    if (jj_scan_token(107)) return true;
    if (jj_3R_82()) return true;
    return false;
  }

  private boolean jj_3R_52()
 {
    if (jj_3R_55()) return true;
    return false;
  }

  private boolean jj_3R_133()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(31)) {
    jj_scanpos = xsp;
    if (jj_3R_134()) return true;
    }
    return false;
  }

  private boolean jj_3R_134()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(35)) {
    jj_scanpos = xsp;
    if (jj_scan_token(108)) {
    jj_scanpos = xsp;
    if (jj_scan_token(28)) return true;
    }
    }
    if (jj_3R_33()) return true;
    return false;
  }

  private boolean jj_3R_54()
 {
    if (jj_scan_token(81)) return true;
    return false;
  }

  private boolean jj_3R_55()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_59()) {
    jj_scanpos = xsp;
    if (jj_3R_60()) {
    jj_scanpos = xsp;
    if (jj_3R_61()) {
    jj_scanpos = xsp;
    if (jj_3R_62()) {
    jj_scanpos = xsp;
    if (jj_3R_63()) {
    jj_scanpos = xsp;
    if (jj_3R_64()) {
    jj_scanpos = xsp;
    if (jj_3_6()) {
    jj_scanpos = xsp;
    if (jj_3R_65()) {
    jj_scanpos = xsp;
    if (jj_3R_66()) {
    jj_scanpos = xsp;
    if (jj_3R_67()) return true;
    }
    }
    }
    }
    }
    }
    }
    }
    }
    return false;
  }

  private boolean jj_3R_59()
 {
    if (jj_scan_token(S_NUMBER)) return true;
    return false;
  }

  private boolean jj_3R_60()
 {
    if (jj_scan_token(S_CHAR_LITERAL)) return true;
    return false;
  }

  private boolean jj_3R_61()
 {
    if (jj_scan_token(K_NULL)) return true;
    return false;
  }

  private boolean jj_3R_62()
 {
    if (jj_3R_70()) return true;
    return false;
  }

  private boolean jj_3R_63()
 {
    if (jj_scan_token(76)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_5()) {
    jj_scanpos = xsp;
    if (jj_3R_75()) return true;
    }
    if (jj_scan_token(78)) return true;
    return false;
  }

  private boolean jj_3R_64()
 {
    if (jj_3R_71()) return true;
    return false;
  }

  private boolean jj_3_6()
 {
    if (jj_3R_25()) return true;
    return false;
  }

  private boolean jj_3R_65()
 {
    if (jj_3R_26()) return true;
    return false;
  }

  private boolean jj_3R_66()
 {
    if (jj_3R_72()) return true;
    return false;
  }

  private boolean jj_3_5()
 {
    if (jj_3R_24()) return true;
    return false;
  }

  private boolean jj_3R_49()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(83)) {
    jj_scanpos = xsp;
    if (jj_scan_token(84)) return true;
    }
    if (jj_3R_46()) return true;
    return false;
  }

  private boolean jj_3R_67()
 {
    if (jj_3R_30()) return true;
    return false;
  }

  private boolean jj_3R_40()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(80)) {
    jj_scanpos = xsp;
    if (jj_scan_token(81)) {
    jj_scanpos = xsp;
    if (jj_scan_token(82)) return true;
    }
    }
    if (jj_3R_38()) return true;
    return false;
  }

  private boolean jj_3R_111()
 {
    if (jj_scan_token(K_WHERE)) return true;
    if (jj_3R_82()) return true;
    return false;
  }

  private boolean jj_3_7()
 {
    if (jj_3R_26()) return true;
    return false;
  }

  private boolean jj_3R_92()
 {
    if (jj_scan_token(K_ORDER)) return true;
    if (jj_scan_token(K_BY)) return true;
    if (jj_3R_98()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_99()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3_8()
 {
    if (jj_3R_27()) return true;
    if (jj_scan_token(76)) return true;
    return false;
  }

  private boolean jj_3R_70()
 {
    if (jj_scan_token(K_CASE)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_79()) {
    jj_scanpos = xsp;
    if (jj_3R_80()) return true;
    }
    xsp = jj_scanpos;
    if (jj_3R_81()) jj_scanpos = xsp;
    if (jj_scan_token(K_END)) return true;
    return false;
  }

  private boolean jj_3R_98()
 {
    if (jj_3R_31()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_103()) jj_scanpos = xsp;
    xsp = jj_scanpos;
    if (jj_3R_104()) jj_scanpos = xsp;
    return false;
  }

  private boolean jj_3R_81()
 {
    if (jj_scan_token(K_ELSE)) return true;
    if (jj_3R_31()) return true;
    return false;
  }

  private boolean jj_3R_103()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(10)) {
    jj_scanpos = xsp;
    if (jj_scan_token(21)) return true;
    }
    return false;
  }

  private boolean jj_3R_104()
 {
    if (jj_scan_token(109)) return true;
    if (jj_3R_33()) return true;
    return false;
  }

  private boolean jj_3R_132()
 {
    if (jj_scan_token(76)) return true;
    if (jj_scan_token(80)) return true;
    if (jj_scan_token(78)) return true;
    return false;
  }

  private boolean jj_3R_25()
 {
    if (jj_scan_token(K_CAST)) return true;
    if (jj_scan_token(76)) return true;
    if (jj_3R_82()) return true;
    if (jj_scan_token(K_AS)) return true;
    if (jj_3R_83()) return true;
    if (jj_scan_token(78)) return true;
    return false;
  }

  private boolean jj_3R_79()
 {
    if (jj_3R_31()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_85()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_80()
 {
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_86()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_86()
 {
    if (jj_scan_token(K_WHEN)) return true;
    if (jj_3R_82()) return true;
    if (jj_scan_token(K_THEN)) return true;
    if (jj_3R_31()) return true;
    return false;
  }

  private boolean jj_3R_20()
 {
    if (jj_3R_30()) return true;
    return false;
  }

  private boolean jj_3R_26()
 {
    if (jj_3R_33()) return true;
    if (jj_3R_31()) return true;
    Token xsp;
    xsp = jj_scanpos;
    jj_lookingAhead = true;
    jj_semLA = "DAY".equalsIgnoreCase(getToken(1).image);
    jj_lookingAhead = false;
    if (!jj_semLA || jj_3R_34()) {
    jj_scanpos = xsp;
    if (jj_3R_35()) return true;
    }
    return false;
  }

  private boolean jj_3R_34()
 {
    if (jj_3R_33()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_41()) jj_scanpos = xsp;
    if (jj_scan_token(111)) return true;
    if (jj_3R_33()) return true;
    xsp = jj_scanpos;
    if (jj_3R_42()) jj_scanpos = xsp;
    return false;
  }

  private boolean jj_3R_28()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_36()) {
    jj_scanpos = xsp;
    if (jj_3R_37()) return true;
    }
    return false;
  }

  private boolean jj_3R_36()
 {
    if (jj_scan_token(S_IDENTIFIER)) return true;
    return false;
  }

  private boolean jj_3R_35()
 {
    if (jj_3R_33()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_43()) jj_scanpos = xsp;
    if (jj_scan_token(111)) return true;
    if (jj_3R_33()) return true;
    xsp = jj_scanpos;
    if (jj_3R_44()) jj_scanpos = xsp;
    return false;
  }

  private boolean jj_3R_75()
 {
    if (jj_3R_82()) return true;
    return false;
  }

  private boolean jj_3R_37()
 {
    if (jj_scan_token(S_QUOTED_IDENTIFIER)) return true;
    return false;
  }

  private boolean jj_3R_72()
 {
    if (jj_3R_27()) return true;
    return false;
  }

  private boolean jj_3R_99()
 {
    if (jj_scan_token(77)) return true;
    if (jj_3R_98()) return true;
    return false;
  }

  private boolean jj_3R_41()
 {
    if (jj_scan_token(76)) return true;
    if (jj_scan_token(S_NUMBER)) return true;
    if (jj_scan_token(78)) return true;
    return false;
  }

  private boolean jj_3R_43()
 {
    if (jj_scan_token(76)) return true;
    if (jj_scan_token(S_NUMBER)) return true;
    if (jj_scan_token(78)) return true;
    return false;
  }

  private boolean jj_3R_27()
 {
    if (jj_3R_30()) return true;
    return false;
  }

  private boolean jj_3R_112()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(86)) {
    jj_scanpos = xsp;
    if (jj_3R_116()) {
    jj_scanpos = xsp;
    if (jj_scan_token(88)) {
    jj_scanpos = xsp;
    if (jj_3_9()) {
    jj_scanpos = xsp;
    if (jj_scan_token(89)) {
    jj_scanpos = xsp;
    if (jj_3_10()) {
    jj_scanpos = xsp;
    if (jj_3_11()) {
    jj_scanpos = xsp;
    if (jj_scan_token(90)) return true;
    }
    }
    }
    }
    }
    }
    }
    return false;
  }

  private boolean jj_3R_116()
 {
    if (jj_scan_token(87)) return true;
    if (jj_scan_token(86)) return true;
    return false;
  }

  private boolean jj_3_9()
 {
    if (jj_scan_token(89)) return true;
    if (jj_scan_token(86)) return true;
    return false;
  }

  private boolean jj_3_10()
 {
    if (jj_scan_token(90)) return true;
    if (jj_scan_token(89)) return true;
    return false;
  }

  private boolean jj_3_11()
 {
    if (jj_scan_token(90)) return true;
    if (jj_scan_token(86)) return true;
    return false;
  }

  private boolean jj_3_16()
 {
    if (jj_scan_token(S_IDENTIFIER)) return true;
    if (jj_scan_token(94)) return true;
    return false;
  }

  private boolean jj_3R_85()
 {
    if (jj_scan_token(K_WHEN)) return true;
    if (jj_3R_31()) return true;
    if (jj_scan_token(K_THEN)) return true;
    if (jj_3R_31()) return true;
    return false;
  }

  private boolean jj_3R_128()
 {
    if (jj_3R_28()) return true;
    return false;
  }

  private boolean jj_3R_42()
 {
    if (jj_scan_token(76)) return true;
    if (jj_scan_token(S_NUMBER)) return true;
    if (jj_scan_token(78)) return true;
    return false;
  }

  private boolean jj_3R_44()
 {
    if (jj_scan_token(76)) return true;
    if (jj_scan_token(S_NUMBER)) return true;
    if (jj_scan_token(78)) return true;
    return false;
  }

  private boolean jj_3R_30()
 {
    if (jj_3R_28()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_45()) jj_scanpos = xsp;
    return false;
  }

  private boolean jj_3R_45()
 {
    if (jj_scan_token(85)) return true;
    if (jj_3R_28()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_50()) jj_scanpos = xsp;
    return false;
  }

  private boolean jj_3R_50()
 {
    if (jj_scan_token(85)) return true;
    if (jj_3R_28()) return true;
    return false;
  }

  private boolean jj_3R_71()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(63)) {
    jj_scanpos = xsp;
    if (jj_3R_76()) return true;
    }
    return false;
  }

  private boolean jj_3R_76()
 {
    if (jj_scan_token(66)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(54)) {
    jj_scanpos = xsp;
    if (jj_scan_token(60)) return true;
    }
    return false;
  }

  private boolean jj_3_12()
 {
    if (jj_scan_token(S_IDENTIFIER)) return true;
    if (jj_scan_token(94)) return true;
    return false;
  }

  private boolean jj_3R_83()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(13)) {
    jj_scanpos = xsp;
    if (jj_scan_token(67)) {
    jj_scanpos = xsp;
    if (jj_scan_token(68)) {
    jj_scanpos = xsp;
    if (jj_scan_token(18)) {
    jj_scanpos = xsp;
    if (jj_scan_token(69)) {
    jj_scanpos = xsp;
    if (jj_scan_token(26)) {
    jj_scanpos = xsp;
    if (jj_scan_token(70)) {
    jj_scanpos = xsp;
    if (jj_scan_token(50)) {
    jj_scanpos = xsp;
    if (jj_scan_token(71)) {
    jj_scanpos = xsp;
    if (jj_scan_token(20)) {
    jj_scanpos = xsp;
    if (jj_scan_token(72)) {
    jj_scanpos = xsp;
    if (jj_scan_token(23)) {
    jj_scanpos = xsp;
    if (jj_scan_token(73)) {
    jj_scanpos = xsp;
    if (jj_scan_token(74)) return true;
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    return false;
  }

  private boolean jj_3R_24()
 {
    if (jj_3R_32()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_87()) jj_scanpos = xsp;
    return false;
  }

  private boolean jj_3R_29()
 {
    if (jj_3R_24()) return true;
    return false;
  }

  private boolean jj_3R_87()
 {
    if (jj_3R_92()) return true;
    return false;
  }

  private boolean jj_3R_32()
 {
    if (jj_3R_39()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_91()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_33()
 {
    if (jj_scan_token(S_IDENTIFIER)) return true;
    return false;
  }

  private boolean jj_3R_96()
 {
    if (jj_scan_token(95)) return true;
    return false;
  }

  private boolean jj_3R_97()
 {
    if (jj_scan_token(96)) return true;
    return false;
  }

  private boolean jj_3R_39()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_47()) {
    jj_scanpos = xsp;
    if (jj_3R_48()) return true;
    }
    return false;
  }

  private boolean jj_3R_47()
 {
    if (jj_3R_53()) return true;
    return false;
  }

  private boolean jj_3R_91()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_95()) {
    jj_scanpos = xsp;
    if (jj_3R_96()) {
    jj_scanpos = xsp;
    if (jj_3R_97()) return true;
    }
    }
    if (jj_3R_39()) return true;
    return false;
  }

  private boolean jj_3R_95()
 {
    if (jj_scan_token(K_UNION)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_102()) jj_scanpos = xsp;
    return false;
  }

  private boolean jj_3R_53()
 {
    if (jj_scan_token(K_SELECT)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_56()) jj_scanpos = xsp;
    if (jj_3R_57()) return true;
    if (jj_3R_58()) return true;
    xsp = jj_scanpos;
    if (jj_3R_106()) jj_scanpos = xsp;
    return false;
  }

  private boolean jj_3R_106()
 {
    if (jj_3R_111()) return true;
    return false;
  }

  private boolean jj_3R_48()
 {
    if (jj_scan_token(76)) return true;
    if (jj_3R_29()) return true;
    if (jj_scan_token(78)) return true;
    return false;
  }

  /** Generated Token Manager. */
  public ParserTokenManager token_source;
  SimpleCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private Token jj_scanpos, jj_lastpos;
  private int jj_la;
  /** Whether we are looking ahead. */
  private boolean jj_lookingAhead = false;
  private boolean jj_semLA;
  private int jj_gen;
  final private int[] jj_la1 = new int[101];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static private int[] jj_la1_2;
  static private int[] jj_la1_3;
  static {
	   jj_la1_init_0();
	   jj_la1_init_1();
	   jj_la1_init_2();
	   jj_la1_init_3();
	}
	private static void jj_la1_init_0() {
	   jj_la1_0 = new int[] {0x0,0x0,0x4942000,0x0,0x0,0x0,0x1,0x0,0x80,0x0,0x0,0x0,0x20001000,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x30000,0x30000,0x10000,0x0,0x0,0x0,0x30000,0x1000000,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x20000000,0x0,0x0,0x0,0x24942000,0x0,0x0,0x0,0x20,0x0,0x0,0x400020,0x400020,0x0,0x0,0x30000,0x30000,0x200,0x200,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x30000,0x30000,0x31000,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x90000000,0x0,0x10000000,0x90000000,0x0,0x200400,0x200400,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x30000,0x8000000,0x30000,0x0,0x0,};
	}
	private static void jj_la1_init_1() {
	   jj_la1_1 = new int[] {0x10400000,0x80000000,0x40000,0x1000,0x0,0x21000,0x0,0x100,0x0,0x40,0x0,0x4,0x54,0x0,0x40,0x40,0x40,0x40,0x0,0x0,0x0,0x0,0x0,0x90400080,0x904000c0,0x80400080,0x10000000,0x100000,0x100000,0x90400080,0x0,0x10000000,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x10400000,0x0,0x0,0x0,0x0,0x40000,0x0,0x200,0x10000,0x0,0x10000,0x1000,0x0,0x0,0x80000,0x0,0x90400080,0x90400080,0x0,0x10100000,0x10100000,0x0,0x400,0x0,0x200,0x0,0x0,0x90400080,0x90400080,0x90400080,0x0,0x0,0x90000000,0x0,0x0,0x90004000,0x10004000,0x80000000,0x0,0x10000000,0x800,0x10000000,0x8,0x0,0x8,0x8,0x0,0x0,0x0,0x0,0x40,0x0,0x0,0x0,0x0,0x10000000,0x0,0x90400080,0x0,0x90400080,0x0,0x0,};
	}
	private static void jj_la1_init_2() {
	   jj_la1_2 = new int[] {0x0,0x4,0x7f8,0x1800,0x2000,0x1000,0x8000,0x0,0x0,0x0,0x7c00000,0x0,0x7c00000,0x2000,0x0,0x0,0x0,0x0,0x70000,0x70000,0x180000,0x180000,0x30000,0x31007,0x31007,0x1005,0x2,0x0,0x0,0x31007,0x0,0x2,0x200000,0x1c00000,0x2000000,0x4000000,0x2000,0x30000,0x30000,0x30000,0x0,0x8000000,0x30000000,0x30000000,0x80007f8,0x2000,0x0,0x80000000,0x0,0x80000000,0x1000,0x0,0x0,0x0,0x2000,0xb1007,0x31007,0x0,0x2,0x2,0x0,0x0,0x0,0x0,0x2000,0x0,0x31007,0x31007,0x31007,0x2000,0x200000,0x4,0x1000,0x2000,0x1006,0x2,0x1004,0x0,0x0,0x0,0x2,0x0,0x1000,0x0,0x0,0x2000,0x0,0x0,0x0,0x0,0x1000,0x1000,0x1000,0x1000,0x0,0x2000,0x31007,0x0,0x31007,0x200000,0x200000,};
	}
	private static void jj_la1_init_3() {
	   jj_la1_3 = new int[] {0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x1,0x0,0x1,0x0,0x2,0x2,0x0,0x0,0x0,0x0,0x0,0x8,0x8,0x10,0x0,0x60,0x0,0x0,0x60,0x80,0x80,0x80,0x0,0x0,0x0,0x0,0x0,0x200,0x0,0x0,0x400,0x0,0x0,0x0,0x1000,0x0,0x1000,0x1000,0x0,0x0,0x0,0x2000,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,};
	}
  private final JJCalls[] jj_2_rtns = new JJCalls[16];
  private boolean jj_rescan = false;
  private int jj_gc = 0;

  /**
   * Constructor with InputStream.
   * @param stream char stream
   */
  public Parser(final Provider stream) {
	 jj_input_stream = new SimpleCharStream(stream, 1, 1);
	 token_source = new ParserTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
   for (int i = 0; i < 101; i++)
     jj_la1[i] = -1;
   for (int i = 0; i < jj_2_rtns.length; i++)
     jj_2_rtns[i] = new JJCalls();
  }

  /**
   * Constructor with InputStream.
   * @param sDSL String representation to be parsed
   */
  public Parser(final String sDSL) {
	   this(new StringProvider(sDSL));
  }

  /**
   * Reinitialise.
   * @param sDSL String representation to be parsed
   */
  public void ReInit(final String sDSL) {
	  ReInit(new StringProvider(sDSL));
  }
  /**
   * Reinitialise
   * @param stream char stream
   */
  public void ReInit(final Provider stream) {
	if (jj_input_stream == null) {
	  jj_input_stream = new SimpleCharStream(stream, 1, 1);
	} else {
	  jj_input_stream.reInit(stream, 1, 1);
  }
	if (token_source == null) {
 token_source = new ParserTokenManager(jj_input_stream);
	}

	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
   for (int i = 0; i < 101; i++)
     jj_la1[i] = -1;
   for (int i = 0; i < jj_2_rtns.length; i++)
     jj_2_rtns[i] = new JJCalls();
  }

  /**
   * Constructor with generated Token Manager.
   * @param tm Token manager to use
   */
  public Parser(final ParserTokenManager tm) {
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 101; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /**
   * Reinitialise
   * @param tm Token manager to use
   */
  public void ReInit(final ParserTokenManager tm) {
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 101; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  private Token jj_consume_token(final int kind) throws ParseException {
    final Token oldToken = token;
    if (token.next != null)
      token = token.next;
    else {
      token.next = token_source.getNextToken();
      token = token.next;
    }
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      if (++jj_gc > 100) {
        jj_gc = 0;
        for (int i = 0; i < jj_2_rtns.length; i++) {
          JJCalls c = jj_2_rtns[i];
          while (c != null) {
            if (c.gen < jj_gen)
              c.first = null;
            c = c.next;
          }
        }
      }
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }

  private static final class LookaheadSuccess extends IllegalStateException {}
  private final LookaheadSuccess jj_ls = new LookaheadSuccess();
  private boolean jj_scan_token(int kind) {
	 if (jj_scanpos == jj_lastpos) {
	   jj_la--;
	   if (jj_scanpos.next == null) {
		   jj_lastpos = jj_scanpos = jj_scanpos.next = token_source.getNextToken();
	   } else {
		   jj_lastpos = jj_scanpos = jj_scanpos.next;
	   }
	 } else {
	   jj_scanpos = jj_scanpos.next;
	 }
	 if (jj_rescan) {
	   int i = 0; Token tok = token;
	   while (tok != null && tok != jj_scanpos) { i++; tok = tok.next; }
	   if (tok != null) jj_add_error_token(kind, i);
	 }
	 if (jj_scanpos.kind != kind) return true;
	 if (jj_la == 0 && jj_scanpos == jj_lastpos) throw jj_ls;
	 return false;
  }


  /**
   * @return the next Token.
   */
  public final Token getNextToken() {
   if (token.next != null)
     token = token.next;
   else
     token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 jj_gen++;
	 return token;
  }

  /**
   * @param index index to be retrieved
   * @return the specific Token.
   */
  public final Token getToken(final int index) {
    Token t = jj_lookingAhead ? jj_scanpos : token;
    for (int i = 0; i < index; i++) {
      if (t.next == null)
        t.next = token_source.getNextToken();
      t = t.next;
    }
    return t;
  }

  private int jj_ntk_f() {
    jj_nt = token.next;
    if (jj_nt == null) {
      token.next = token_source.getNextToken();
      jj_ntk = token.next.kind;
      return jj_ntk;
    }
    jj_ntk = jj_nt.kind;
    return jj_ntk;
  }

  private java.util.List<int[]> jj_expentries = new java.util.ArrayList<>();
  private int[] jj_expentry;
  private int jj_kind = -1;
  private int[] jj_lasttokens = new int[100];
  private int jj_endpos;

  private void jj_add_error_token(int kind, int pos) {
  if (pos >= 100) {
    return;
  }

  if (pos == jj_endpos + 1) {
    jj_lasttokens[jj_endpos++] = kind;
  } else if (jj_endpos != 0) {
    jj_expentry = new int[jj_endpos];

    for (int i = 0; i < jj_endpos; i++) {
      jj_expentry[i] = jj_lasttokens[i];
    }

    for (final int[] oldentry : jj_expentries) {
      if (oldentry.length == jj_expentry.length) {
        boolean isMatched = true;
        for (int i = 0; i < jj_expentry.length; i++) {
          if (oldentry[i] != jj_expentry[i]) {
            isMatched = false;
            break;
          }
        }
        if (isMatched) {
          jj_expentries.add(jj_expentry);
          break;
        }
      }
    }

    if (pos != 0) {
      jj_endpos = pos;
      jj_lasttokens[jj_endpos - 1] = kind;
    }
  }
}

  /**
   * Generate ParseException.
   * @return new Exception object. Never <code>null</code>
   */
  public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[112];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 101; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
          if ((jj_la1_1[i] & (1<<j)) != 0) {
            la1tokens[32+j] = true;
          }
          if ((jj_la1_2[i] & (1<<j)) != 0) {
            la1tokens[64+j] = true;
          }
          if ((jj_la1_3[i] & (1<<j)) != 0) {
            la1tokens[96+j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 112; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    jj_endpos = 0;
    jj_rescan_token();
    jj_add_error_token(0, 0);
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage, token_source == null ? null : ParserTokenManager.lexStateNames[token_source.curLexState]);
  }

  /**
   * @return Always <code>false</code>.
   */
  public final boolean trace_enabled() {
    return false;
  }

  /** Enable tracing. */
  public final void enable_tracing() {}

  /** Disable tracing. */
  public final void disable_tracing() {}

  private void jj_rescan_token() {
    jj_rescan = true;
    for (int i = 0; i < 16; i++) {
      try {
        JJCalls p = jj_2_rtns[i];
        do {
          if (p.gen > jj_gen) {
            jj_la = p.arg;
            jj_scanpos = p.first;
            jj_lastpos = p.first;
            switch (i) {
              case 0: jj_3_1(); break;
              case 1: jj_3_2(); break;
              case 2: jj_3_3(); break;
              case 3: jj_3_4(); break;
              case 4: jj_3_5(); break;
              case 5: jj_3_6(); break;
              case 6: jj_3_7(); break;
              case 7: jj_3_8(); break;
              case 8: jj_3_9(); break;
              case 9: jj_3_10(); break;
              case 10: jj_3_11(); break;
              case 11: jj_3_12(); break;
              case 12: jj_3_13(); break;
              case 13: jj_3_14(); break;
              case 14: jj_3_15(); break;
              case 15: jj_3_16(); break;
            }
          }
          p = p.next;
        } while (p != null);
      } catch(LookaheadSuccess ls) { /* ignore */ }
    }
    jj_rescan = false;
  }

  private void jj_save(int index, int xla) {
    JJCalls p = jj_2_rtns[index];
    while (p.gen > jj_gen) {
      if (p.next == null) {
        p.next = new JJCalls();
        p = p.next;
        break;
      }
      p = p.next;
    }
    p.gen = jj_gen + xla - jj_la; 
    p.first = token;
    p.arg = xla;
  }

  static final class JJCalls {
	 int gen;
	 Token first;
	 int arg;
	 JJCalls next;
  }

}
